spring:
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848
    elasticsearch:
      rest:
        uris: http://192.168.194.128:9200
    jackson:
      default-property-inclusion: non_null
    rabbitmq:
      host: 192.168.194.128
      virtual-host: /taolin
      username: taolin
      password: 135820qwe
server:
  port: 8086

